package org.campusmolndal.todoapi.model;

import java.time.LocalDate;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.*;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;


@Data
@AllArgsConstructor
@NoArgsConstructor
@Entity
public class Todo {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Schema(description = "Identifier value", example = "1")
    private Long id;

    @Schema(description = "Name for todo object", example = "dishes")
    private String title;

    @Schema(description = "Description for what to do", example = "do the dishes")
    private String description;

    @Schema(description = "Date todo got created, autogenerated for POST, ignored for PUT.", example = "yyyy-mm-dd")
    private LocalDate creationDate;

    @Schema(description = "Date for which task is to be completed", example = "2024-11-11")
    private LocalDate deadLine;

    @Schema(description = "boolean for wether task is completed", example = "true")
    private boolean completed;

    public Todo setId(Long id) {
        this.id = id;
        return this;
    }
}
